[package]
name = "duckdb_fuzzycomplete_rust"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "duckdb_fuzzycomplete_rust"
crate-type = ["staticlib"]

[dependencies]
code-fuzzy-match = "0.2.2"
